apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wic-ingress-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - wic{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{- if ne .Release.Namespace "production" }}cs.{{- end }}calvin.edu
    secretName: tls-secret-wic-{{ default "staging" .Release.Namespace }}
  rules:
  - host: wic{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{- if ne .Release.Namespace "production" }}cs.{{- end }}calvin.edu
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: wic-{{ default "staging" .Release.Namespace }}
            port:
              number: 80
